### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by IanWONeill** [Explv/Explv.github.io#1]
Are you going to be pushing an update to this?
Or alternatively explain how your doing it so as someone can take over the project?
I use this at https://rune-status.net/tools/map/

**Comment by Explv** [comment]
@IanWONeill I am aiming to push an update this weekend. I will also add a tool to the repo to demonstrate how the map is generated.

**Comment by IanWONeill** [comment]
Sounds good, and how are you expecting the auto-upd-sys to work? Do you have a way in-mind for that sort of project?

I don't know if your interested but feel free to come chat(shit) in the Rune-Status Discord (mainly RSPS developers) : https://discord.gg/eCz3y4r

More than welcome - may even be able to get some ideas from the guys in there, the most active people are all working on OSRS Private Servers at the minute.. so may have some nice insight for you.

**Comment by Explv** [comment]
@IanWONeill updated.
