### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by osrsbox** [Explv/Explv.github.io#11]
Hi @Explv. I couldn't find an email or other contact details, so ended up posting an issue here.

I was wanting to use your map as a base for a project I am working on - the project is querying NPCs for location data in-game, then mapping them onto a world map. I couldn't find any license for this map project and wanted to check with you about potential reuse (basically would like to fork and modify for my project).

**Comment by Explv** [comment]
As long as you credit me I have no issue

**Comment by osrsbox** [comment]
Thanks @Explv - more than happy to credit you. Also- thanks for the quick reply, and thanks for making (and sharing) such a great resource. Closing the issue as it is resolved.
