### ISSUE TITLE
[Bug] Map titles are outdated

### ISSUE THREAD

**Issue by Bia10** [Explv/Explv.github.io#20]
The map doesn't reflect the current OSRS map tiles as of 2022.
![Shayzien](https://user-images.githubusercontent.com/2548763/152464943-d8bd455b-67be-4270-81df-da8b5638b71c.png)
![iceberg](https://user-images.githubusercontent.com/2548763/152464947-1d8c1313-3ec0-4c6b-a251-5a3142271ac3.png)

Edit: Yes, surely I can generate my own, but why should every user has to do this when the map titles don't change so often anyways and the process is so freakin slow.

**Comment by Explv** [comment]
I do have a script which diffs the new map with the old map and only regenerates changed tiles. It isn't quite ready for public use though.

Ideally all of this would be automated, it's definitely not hard to do, just takes a bit of time to setup, which unfortunately I don't have at the moment.

Anyway, another user has kindly updated the map for you
