### ISSUE TITLE
Dax Path functionality broken

### ISSUE THREAD

**Issue by Tyrannosaurus1234** [Explv/Explv.github.io#29]
Attempting to use the Dax Path functionality leads to the following error: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://osrs-map.herokuapp.com/getPath. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 503.` which to me sounds like the Heroku instance your map feeds requests through got knocked offline.

**Comment by Explv** [comment]
Yeah, you're right that the heroku server no longer exists. I'll look for a solution, thanks

**Comment by Explv** [comment]
Fixed
